#### Target Guided Ordinal Encoding 
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [1]:
import pandas as pd
# create a sample dataframe with a categorical variable and a target variable

df=pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [2]:
df.head(5)

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180

In [3]:
df.groupby('city')['price'].mean()

city
London      150.0
New York    190.0
Paris       310.0
Tokyo       250.0
Name: price, dtype: float64

In [4]:
df.groupby('city')['price'].count()

city
London      1
New York    2
Paris       2
Tokyo       1
Name: price, dtype: int64

In [5]:
mean_price=df.groupby('city')['price'].mean().to_dict()
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [6]:
df['city_encoded']=df['city'].map(mean_price)

In [7]:
df.head()

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0

In [8]:
! pip install feature-engine

Requirement already satisfied: feature-engine in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (1.9.4)
Requirement already satisfied: numpy>=1.18.2 in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (from feature-engine) (1.26.4)
Requirement already satisfied: pandas>=2.2.0 in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (from feature-engine) (2.2.2)
Requirement already satisfied: scikit-learn>=1.4.0 in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (from feature-engine) (1.5.1)
Requirement already satisfied: scipy>=1.4.1 in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (from feature-engine) (1.13.1)
Requirement already satisfied: statsmodels>=0.11.1 in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (from feature-engine) (0.14.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (from pandas>=2.2.0->feature-engine) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (from pandas>=2.2.0->feature-engine) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (from pandas>=2.2.0->feature-engine) (2023.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (from scikit-learn>=1.4.0->feature-engine) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (from scikit-learn>=1.4.0->feature-engine) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (from statsmodels>=0.11.1->feature-engine) (0.5.6)
Requirement already satisfied: packaging>=21.3 in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (from statsmodels>=0.11.1->feature-engine) (24.1)
Requirement already satisfied: six in c:\users\abhadori\appdata\local\anaconda3\lib\site-packages (from patsy>=0.5.6->statsmodels>=0.11.1->feature-engine) (1.16.0)

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from feature_engine.encoding import OrdinalEncoder

df = pd.DataFrame({
    'City':['Delhi','Mumbai','Delhi','Chennai','Mumbai',
            'Delhi','Chennai','Pune','Pune','Delhi'],
    'Purchased':[1,0,1,0,1,1,0,1,0,1]
})

X = df[['City']]
y = df['Purchased']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

encoder = OrdinalEncoder(
    encoding_method='ordered',
    variables=['City']
)

encoder.fit(X_train, y_train)

print(encoder.encoder_dict_)

X_train = encoder.transform(X_train)
X_test = encoder.transform(X_test)

print(X_train.head())

{'City': {'Chennai': 0, 'Delhi': 1, 'Mumbai': 2, 'Pune': 3}}
   City
0     1
7     3
2     1
9     1
4     2