In [3]:
import pandas as pd
import numpy as np

Pivot Tables are used to summarize and aggregate data in a tabular format. They allow you to transform and reshape your data, making it easier to analyze and visualize. In this notebook, we will explore how to create pivot tables using the Pandas library in Python.

In [4]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': [
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South'
    ],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': [
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice'
    ]
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    475     64   John  January      Q1
1  2023-01-02       B   West    753     68   Mary  January      Q1
2  2023-01-03       C  North    976     88    Bob  January      Q1
3  2023-01-04       D  South    258     47  Alice  January      Q1
4  2023-01-05       A   East    335     30   John  January      Q1
5  2023-01-06       B   West    964     38   Mary  January      Q1
6  2023-01-07       C  North    233     51    Bob  January      Q1
7  2023-01-08       D  South    480     53  Alice  January      Q1
8  2023-01-09       A   East    180     96   John  January      Q1
9  2023-01-10       B   West    937     35   Mary  January      Q1
10 2023-01-11       C  North    428     76    Bob  January      Q1
11 2023-01-12       D  South    764     78  Alice  January      Q1
12 2023-01-13       A   East    750     66   John  January      Q1
13 2023-01-14       B   West    167     58   Mary  January      Q1
14 2023-01-15       C  North    430     80    Bob  January      Q1
15 2023-01-16       D  South    477     39  Alice  January      Q1
16 2023-01-17       A   East    613     36   John  January      Q1
17 2023-01-18       B   West    744     21   Mary  January      Q1
18 2023-01-19       C  North    675     92    Bob  January      Q1
19 2023-01-20       D  South    903     87  Alice  January      Q1

In [5]:
pd.pivot_table(df,values='Sales', index='Region', columns='Product', aggfunc='sum', fill_value=0)

Product     A     B     C     D
Region
East     2353     0     0     0
North       0     0  2742     0
South       0     0     0  2882
West        0  3565     0     0

In [6]:
pd.pivot_table(df,values=['Sales','Units'], index='Region', columns='Product', aggfunc='sum', fill_value=0)

        Sales                   Units
Product     A     B     C     D     A    B    C    D
Region
East     2353     0     0     0   292    0    0    0
North       0     0  2742     0     0    0  387    0
South       0     0     0  2882     0    0    0  304
West        0  3565     0     0     0  220    0    0

Cross Tabs

In [7]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [8]:
pd.crosstab(df["Region"], df["Product"], margins=True)

Product  A  B  C  D  All
Region
East     5  0  0  0    5
North    0  0  5  0    5
South    0  0  0  5    5
West     0  5  0  0    5
All      5  5  5  5   20

In [9]:
pd.crosstab(
    df["Region"],
    df["Product"],
    normalize=True
)

Product     A     B     C     D
Region
East     0.25  0.00  0.00  0.00
North    0.00  0.00  0.25  0.00
South    0.00  0.00  0.00  0.25
West     0.00  0.25  0.00  0.00

In [10]:
pd.crosstab(
    df["Region"],
    df["Product"],
    normalize="index"
)

Product    A    B    C    D
Region
East     1.0  0.0  0.0  0.0
North    0.0  0.0  1.0  0.0
South    0.0  0.0  0.0  1.0
West     0.0  1.0  0.0  0.0

In [11]:
pd.crosstab(
    df["Region"],
    df["Product"],
    normalize="columns"
)

Product    A    B    C    D
Region
East     1.0  0.0  0.0  0.0
North    0.0  0.0  1.0  0.0
South    0.0  0.0  0.0  1.0
West     0.0  1.0  0.0  0.0